name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}